import "./globals.css";
import NextAuthProvider from "../context/NextAuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body>
            {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}